### ISSUE TITLE
Info on lunches

### ISSUE THREAD

**Issue by pgleeson** [OCNS/Website#12]
There should be a clear place where the info on lunches that Michele sent is displayed, not just on the registration forms.

Maybe add a link to a page Lunches & Dinners under Venue Info (possibly change this heading to General Info?). Local restaurant info can be added here too...

**Comment by pgleeson** [comment]
@yger you should find out from Michele about exactly how long in advance lunches need to be ordered. The forms and http://www.cnsorg.org/cns-2017-lunches seem to suggest that you can only order these at the time of main registration. Should be updated to say:
Lunches must be reserved in advance (up to XX June?), and can be paid for at the time of registration, or can be added to the registration as outlined here: http://www.cnsorg.org/cns-2016-add-to-registration-fees

**Comment by yger** [comment]
I'll ask him asap

Best

Pierre

2017-03-09 12:42 GMT+01:00 Padraig Gleeson <notifications@github.com>:
