### ISSUE TITLE
Link to http://www.cnsorg.org/cns-2017-add-to-registration-fees

### ISSUE THREAD

**Issue by pgleeson** [OCNS/Website#14]
http://www.cnsorg.org/cns-2017-add-to-registration-fees should be set to public & have updated links to the 2 add to reg forms

This should be added on main meeting page under Add to registration; currently linking to one of the forms.

Broken link to 2016 page on http://www.cnsorg.org/cns-2017-registration-fees

**Comment by yger** [comment]
This has been corrected, thanks for the feedback

2017-03-09 12:46 GMT+01:00 Padraig Gleeson <notifications@github.com>:
