### ISSUE TITLE
Minor tweaks

### ISSUE THREAD

**Issue by pgleeson** [OCNS/Website#15]
- Remove "Follow us" and "Attendee info" on main cns2017 page
- Add contact emails for tutorials & workshops on the relevant pages
- Link to http://www.cnsorg.org/cns-2017-lunches on reg fees page 
- Fix links to http://www.cnsorg.org/cns-2017-workshops on Calendar
- Update non member fees to late reg level

**Comment by yger** [comment]
You mean to remove the whole "Attendee section" ? And what do you mean by "Add contact emails for tutorials & workshops on the relevant pages" ? All contacts are up-to-date on the tutorials and workshops pages (from what I received), but you mean to update it somewhere else?

**Comment by pgleeson** [comment]
I meant there is nothing below
![selection_267](https://cloud.githubusercontent.com/assets/1556687/26004992/8cffb71c-372f-11e7-95cf-8f814ab367b7.png)
Either it's needed there or not, prob not if the info is in the menu on the left...

I was suggesting adding a line near the top of the Workshops page: For enquiries related to these workshops, please contact the workshop organiser: workshops@cnsorg.org 
& similar on Tutorials

**Comment by yger** [comment]
Done
