### ISSUE TITLE
Add dates for main meeting/tutorials/workshops to calendar

### ISSUE THREAD

**Issue by pgleeson** [OCNS/Website#16]
Would be convenient for anyone who's not attended the meeting before to see the tutorials (& reception..) are beforehand and workshops afterwards.

**Comment by yger** [comment]
Thanks for the hint. I updated the page "Main Meeting" and the link is now
available on the main page, with a table summarizing what I currently know
about the skeleton of the meeting. Do you think this is enough?

2018-02-05 13:27 GMT+01:00 Padraig Gleeson <notifications@github.com>:

**Comment by pgleeson** [comment]
Great, but that page will eventually be fleshed out with the full info on the meeting incl all talks. It was handy having this level of detail on the calendar page: http://www.cnsorg.org/cns-2018-calendar with just links to the tutorials/main meeting page etc. for a quick overview.

**Comment by yger** [comment]
Ok, done

2018-02-05 19:16 GMT+01:00 Padraig Gleeson <notifications@github.com>:
