### ISSUE TITLE
State explicitly whether abstracts can be edited after submission on ConfMaster

### ISSUE THREAD

**Issue by pgleeson** [OCNS/Website#17]
The new form looks good, but it's not clear whether this can be edited after submission, or just saved for later prior to full submission. It's a lot of info to fill in if you only get one chance.

Would be good to mention this now on the abstract submission info page on cnsorg.org and get ConfMaster to make it clear on their site for next year that it can (and of course implement that feature if it's not there).

**Comment by yger** [comment]
Ok, I'll try to take that into account for next year, and we'll work on the transition between OCNS and ConfMaster. Thanks for the feedback!!!

**Comment by pgleeson** [comment]
I submitted an abstract this year and saw in the conf email that the author list was not in the correct order (I did have to reorder them, but thought I left it in the correct order).

It seems to be still having the issue with not seeing I'm registered, but apart from that, is the only current way to edit an existing abstract to delete it and start again?

**Comment by sanjayankur31** [comment]
@pgleeson I'm not sure and I can't currently log-in to check. I seem to remember editing the abstract when I'd submitted last year to correct the author list.

I've filed  a separate ticket for this (#21), and I'll ask Confmaster admin to fix it too.

**Comment by sanjayankur31** [comment]
I do not currently see an option to edit submissions. I've asked Confmaster admin to confirm if it can be done or not. I'll update this ticket when I have the info.

**Comment by sanjayankur31** [comment]
Editing has been enabled. Closing this now.
