### ISSUE TITLE
Add a Conference Code of Conduct statement

### ISSUE THREAD

**Issue by pgleeson** [OCNS/Website#18]
e.g. use template at http://confcodeofconduct.com or http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy

**Comment by sanjayankur31** [comment]
Mailed the Board asking about this now.

**Comment by pgleeson** [comment]
Cheers. Might never be needed, but best to have it in place before an incident requires it.

**Comment by sanjayankur31** [comment]
It is now live at: https://www.cnsorg.org/code-of-conduct
