### ISSUE TITLE
Make link to Encyclopedia of Computational Neuroscience more prominent

### ISSUE THREAD

**Issue by pgleeson** [OCNS/Website#19]
The fact that CNS members get free access to the ECN should be more prominent on https://www.cnsorg.org/member-benefits, perhaps explicitly added as a numbered item on that page, giving a link that works only if you're logged in as an OCNS member.

- [ ] Also, typo in Ressources on that page...

**Comment by yger** [comment]
Thanks for the advice. I've updated the link such that now, when you are logged in, you should get full access to the Encyclopedia, and fixed the typos. I'm still not sure if I should add a new entry in the Resources menu just for that, I'll think about it

**Comment by pgleeson** [comment]
Thanks. Have just tried it... I seem to be able to get to https://ocns.memberclicks.net/encyclopedia-of-computational-neuroscience without being logged in... Also, the springer articles from there seem to be accessible when I click from not logged in too.

Might be simplest just to restrict access to the above page for logged in people. Also you should maybe add a link on https://www.cnsorg.org/member-benefits like "Members who are logged in can access the encyclopedia here". Was hard to find otherwise.

**Comment by sanjayankur31** [comment]
This seems to be fixed already. The page requires users to be logged in, and the member-benefits page mentions the encyclopedia also. Closing.
