### ISSUE TITLE
Incorrect registration status on Confmaster

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/Website#22]
**Describe the bug**
Confmaster does not correctly recognise registrations from time to time---users are unable to submit abstracts when this happens.

**To Reproduce**
Login to confmaster---intermittently it will incorrectly say "You do not appear to be registered".

**Expected behavior**
Should correctly pick registration status from Memberclicks

**Comment by thomas-preuss** [comment]
A new version is deployed. Should do not happen anymore.

**Comment by sanjayankur31** [comment]
Not re-opening but noting that we've received an e-mail this morning from a user that experienced this issue.

**Comment by thomas-preuss** [comment]
We had to restart the server this morning - may be it happend in this context.

We will keep an eye on it.
