### ISSUE TITLE
Page abstract submission view formatting errors

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/Website#23]
**Describe the bug**
We've received a report that the formatting of the abstract submission page is quite off, making it hard to submit abstracts.

**Screenshots**
![cns-formatting](https://user-images.githubusercontent.com/102575/53303232-f251b380-385f-11e9-9ecb-6b188ee75831.png)

**Comment by thomas-preuss** [comment]
Fixed. 

If still appears: delete browser cache or use another browser / computer.

**Comment by sanjayankur31** [comment]
Thanks very much @thomas-preuss. Closing this now.
