### ISSUE TITLE
Clarify 3500 character limit: is it with or without spaces?

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/Website#25]
@thomas-preuss - a user emailed to ask whether the submission limit includes spaces. I wasn't sure---could you please confirm?

**Comment by thomas-preuss** [comment]
I guess, we count spaces as well:
`len(bleach_strip_html(abstract))`

**Comment by sanjayankur31** [comment]
Thanks very much. I'll let the user know and mention this on our abstract submission page also.
