### ISSUE TITLE
Issues with Chrome

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/Website#27]
We received a report about the wordcounts being computed incorrectly on Chrome:

> Hello. Abstracts for the conference are to be 3,500 characters or less in
> length. When you paste your text into the box there's a character counter below
> it and if you are not within the limit it doesn't let you submit it.
> 
> The character count for abstract submission was giving incorrect counts in
> Chrome, but worked fine in Safari. In chrome, it would give me various
> character counts each time I copied and pasted the same text. 

I will ask for more information on the issue too.

**Comment by sanjayankur31** [comment]
![confmaster-chrome](https://user-images.githubusercontent.com/102575/54036662-1bedd180-41b4-11e9-901c-6db08c687aa6.png)
![confmaster-chrome-info](https://user-images.githubusercontent.com/102575/54036663-1bedd180-41b4-11e9-9c80-f62a0f5774b0.png)

^Info from one user

**Comment by sanjayankur31** [comment]
I will check this again in a couple of hours. I feel like it has something to do with the university tinkering with their DNS settings.

**Comment by thomas-preuss** [comment]
Please re-check.

In any case, you can use the chrome developer tools (CTRL-SHIFT-I --> Network) to see, if it loads all js and css files.

**Comment by sanjayankur31** [comment]
Yes, I can access things fine from home here. Closing this.
