### ISSUE TITLE
Do not pick information from past profiles

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/Website#31]
@thomas-preuss when submitting abstracts, does the form make use of data that the authors may have submitted in the past (or as part of their profiles?) 

A few cases have been reported where the affiliation has changed completely from what was filled out in the form on submission and users have said it looked like it had picked up information that they may have entered in the system in the past?

(These users were using Chrome as their browser too, and since we've had a few issues with Chrome users already, it may be the issue here)

**Comment by thomas-preuss** [comment]
We use the email address as a primary key.

See the blue comment on the submission site:

> For co-authors that are existing users of confmaster, please ask them to edit their personal information in their user profile if changes are necessary. The information of user profiles supersedes the information given during abstract submission. Only edit author information for new authors on the abstract submission form.
