### ISSUE TITLE
Having secondary e-mail on Confmaster causes registration check to fail

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/Website#32]
(Too late for this years submissions)

We've received a few reports of users who have had issues with Confmaster detecting their registration when they have had secondary e-mail addresses set up on Confmaster.

Removing the secondary e-mail address gets it working again.

Could confmaster either check all e-mail addresses, or only check the primary one?

**Comment by thomas-preuss** [comment]
Can you provide us the user name?

We will test.

**Comment by sanjayankur31** [comment]
I've forwarded you the e-mail we received (and fixed by requesting the user to remove the secondary e-mail account)

**Comment by thomas-preuss** [comment]
Should be fixed.

(Memberclick returned a 204 instead of a 200 in the case of a non-existing email address. Now we handle this appropriate.)

**Comment by sanjayankur31** [comment]
Thanks very much. Has the new version been deployed (just received another e-mail that appears to be related to this issue).
