### ISSUE TITLE
Add a "report an issue" form

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/Website#41]
A form to report issues with Confmaster is needed. It needs to be simple:

- a text box for summary
- a text box for description

Submitting this form should send an e-mail to the OCNS webmaster, and Confmaster admins and include this additional information:

- username of user
- time of submisison
- version and build of Confmaster

This will make debugging much easier in the future, and especially not require users to e-mail us separately and us asking them for information that is then forwarded to multiple people and so on.

A link to this form can be added in the footer where it is clearly visible.

**Comment by yger** [comment]
Good idea!

Le 12/03/2019 à 10:28, Ankur Sinha a écrit :

**Comment by thomas-preuss** [comment]
We act as second level support and do not want be involved in all issues.

**Comment by sanjayankur31** [comment]
> We act as second level support and do not want be involved in all issues.

Sure, that's fine. Could the form be set up to e-mail OCNS at webmaster@cnsorg.org? The idea is that when users run into an issue, they do not provide enough information for us to act on it. Most of the time, we have to go back and forth to request information before we can decide if the issue must be forwarded to you. A majority of this results in "well, I don't know what I did".

So:

- let users report issues using a form
- send this report to webmaster@cnsorg.org
- the information we need:
  - username of submitter
  - time issue cropped up
  - issue description
  - any file attachments
  - version of confmaster deployment

This will give us (OCNS) enough information, and if it needs to be forwarded to you, we can do that too. How does this sound?

**Comment by sanjayankur31** [comment]
Could this be implemented @thomas-preuss ?

**Comment by thomas-preuss** [comment]
We could implement this: efforts ~14 hrs.

But why you do not add an email address and ask users to report to this address?

**Comment by sanjayankur31** [comment]
> We could implement this: efforts ~14 hrs.

Ah, really? I thought it'd be simpler.
 
> But why you do not add an email address and ask users to report to this address?

We already do. But these rarely contain enough information for either us to take any steps or to be able to forward it to you.
