### ISSUE TITLE
Freeze production version: only update after tested in staging

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/Website#43]
We had a few issues with deployments of new Confmaster versions. it'll be better to have these tested in a staging environment before the production deployment is updated, especially if abstract submission is open. Ideally, the system should be tested before abstract submission is opened and then frozen there.

**Comment by thomas-preuss** [comment]
A separate staging environment is a good idea, but really expensive. 

Please tell us the hot submission period and we will restrict updates to a minumum.

**Comment by sanjayankur31** [comment]
OK, I'll inform you of the submission dates as soon as they have been fixed. Would it please be possible to send a notification to webmaster@cnsorg.org when the deployment has been modified in any way?

**Comment by thomas-preuss** [comment]
We could do this, at least during the hot usuage period for cns.

**Comment by sanjayankur31** [comment]
Great. That's good to hear.
