### ISSUE TITLE
Create dummy accounts to test abstract submission

### ISSUE THREAD

**Issue by sanjayankur31** [OCNS/Website#44]
Before abstract submission is opened, submission should be tested using dummy registration accounts. An account for each registration type will need to be created, and then tested on Confmaster. 

This year, for example, we experienced issues with student registrants only. These tests will ensure these are caught in time.

**Comment by thomas-preuss** [comment]
You can do this without any problem.

**Comment by sanjayankur31** [comment]
Yes, leaving it open so we (OCNS) don't forget.
