### ISSUE TITLE
The website don't allow me to submit abstract even after I registered and my bank confirmed the conference took the money.

### ISSUE THREAD

**Issue by qius5** [OCNS/Website#48]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sanjayankur31** [comment]
Can you please contact us on webmaster AT cnsorg DOT org with your username/e-mail so we can look into this? Thanks.

**Comment by qius5** [comment]
My user name is ***@***.***, but they do not respond me yet. I sent
them emails about the issue that I can not submit even after registration
and renew my membership multiple times.

**Comment by sanjayankur31** [comment]
You cannot share your e-mail over GitHub. All e-mails that came through to us have now been replied to. Please respond there if you need to.
